replicaCount: 3

deployment:
  name: python-app-prod
service:
  name: python-app-prod-svc
ingress:
  name: python-app-prod-ingress
  hosts:
    - host: python-app.chukwuanugo.biz
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
