replicaCount: 2

deployment:
  name: python-app-uat
service:
  name: python-app-uat-svc
ingress:
  name: python-app-uat-ingress
  hosts:
    - host: python-app-uat.chukwuanugo.biz
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

autoscaling:
  enabled: false
